### ISSUE TITLE
Error while handling push webhook

### ISSUE THREAD

**Issue by udiboy1209** [rvagg/github-webhook-handler#31]
```
1|autodepl | TypeError: this is not a typed array.
1|autodepl |     at Function.from (native)
1|autodepl |     at verify (/var/www/autodeploy/node_modules/github-webhook-handler/github-webhook-handler.js:40:28)
1|autodepl |     at BufferList._callback (/var/www/autodeploy/node_modules/github-webhook-handler/github-webhook-handler.js:80:12)
1|autodepl |     at BufferList.end (/var/www/autodeploy/node_modules/github-webhook-handler/node_modules/bl/bl.js:98:10)
1|autodepl |     at IncomingMessage.onend (_stream_readable.js:498:10)
1|autodepl |     at IncomingMessage.g (events.js:260:16)
1|autodepl |     at emitNone (events.js:67:13)
1|autodepl |     at IncomingMessage.emit (events.js:166:7)
1|autodepl |     at endReadableNT (_stream_readable.js:913:12)
1|autodepl |     at nextTickCallbackWith2Args (node.js:442:9)
```

Can't understand why this error is occuring. I'm using Node 4.4.2

**Comment by rvagg** [comment]
Hey @udiboy1209, unfortunately you're using a version of Node.js that's a little bit too old. We're currently up to v4.8.7 on the v4 series and `Buffer.from()` was introduced later than the one you're on which is why we're seeing a problem here. Can you upgrade your Node.js version? You should at least be on v4.8.7 for security reasons. Ideally you should pick a v8.x release. If you're on Linux and need a source for Node.js go to https://github.com/nodesource/distributions for instructions on how to get a properly updated one.
